### ISSUE TITLE
WU download connection fails or hangs silently, and the client does nothing

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#78]
In Slack, Joe_h has reported this a couple times for v8.1.4 or newer on a Mac (I think). For him: "Only clean method of recovering I have found is a system reboot." "As best as I can tell, I did not run into this hanging download problem until recent builds of v8.  Not certain whether the first time was with 8.1.3 or 8.1.4.  I do know it has stayed that way for over 12 hours."

I have only had this happen once on Windows today with v8.1.7, so far. I normally run FAH on dedicated Linux PCs, and it hasn't happened yet in the last week with v8.1.5 to v8.1.7.

Doing 'Pause', then 'Start' folding didn't do anything (It should have noticed it didn't have a WU yet, and retried downloading the WU, or something).
![image](https://user-images.githubusercontent.com/20870053/210714848-016c3251-4ab6-4296-9820-2e6dd2bb9463.png)
To fix FAH sitting idle and not downloading a WU in v8.1.7, I had to 'dump' the WU and 'start' folding again to get a different WU to download.
```
04:49:19:I1:/RG1:WU3:Requesting WU assignment
04:49:19:D3:/RG1:WU3:{
04:49:20:I1:/RG1:WU3:Received WU assignment nE-bhr9a4uz34DOdDSI7Jqk3KUd57eYc0LBXzIhVVvw
04:49:20:D3:/RG1:WU3:{
04:49:20:D3:/RG1:WU3:Received assignment for 1 cpus and 1 gpus
04:49:20:I1:/RG1:WU3:Downloading WU
04:49:20:I1:OUT16:> POST https://vav19.fah.temple.edu/api/assign HTTP/1.1
04:49:20:I3:Connecting to vav19.fah.temple.edu:443
04:49:20:D1:/RG1:Remaining CPUs: 0, Remaining GPUs: 0, Active WUs: 1 
```
There was no OUT16 HTTP response, and the client did nothing for this WU. I waited 30 minutes, and still nothing.
Debug-version log from Windows (probably not useful): [log-20230104-224318.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/10350070/log-20230104-224318.txt) Look for the log entries above in the middle of the log file.

There were (2) WU download request at about the same time, when 'Starting All', which might have contributed to the connection failure. The PC was bogged down with a lot of things running, and that could have created some slowness for the PC, too.
Ideally, FAH should recognize the connection error and try again, or have a connection timeout after 5 minutes for a retry.

**Comment by Hou5e** [comment]
The next GPU WU was the same on this PC. It didn't download a WU with the PC being heavily used by CPU folding and other things. Normally there would be downloading % messages, and there were none of those because the PC was too busy with CPU folding... [log-20230105-014726.txt](https://github.com/FoldingAtHome/fah-client-bastet/files/10351117/log-20230105-014726.txt)

**Comment by jcoffland** [comment]
This must be a connection failing to timeout out issue.  Otherwise, pausing and unpausing would restart the WU.

**Comment by jcoffland** [comment]
I've digging in to this.   I believe may be Windows only problem but there was mention of macOS above.  I don't think it affects Linux.  Both macOS and Windows use a slightly different core networking code due to both lacking the ``epoll()`` function.

There is a 45s timeout set already but for some reason it's not triggering.  I've confirmed that it's not the DNS lookup but the connect stage that is the problem.  As can be seen in the log connection ``16`` is attempted but then nothing else happens.  The WU continues to wait because the connection is still pending but it never times out.  I could hack around this by adding another timer in the client but I'd like to fix the actually problem in the networking code for Windows.

It would be helpful if someone could run the Windows debug client with this option in ``config.xml``:

    <log-domain-levels v="FD:4,Transfer:4,SSL:5"/>

The above will enable some extra logging related to the problem.

**Comment by jcoffland** [comment]
Never  mind, I think I find the problem.

**Comment by Hou5e** [comment]
It looked like it hung and didn't get very far after setting it up and starting the RGs. I let it run for 20 minutes and it made an 85MB log file: [log.zip](https://github.com/FoldingAtHome/fah-client-bastet/files/10360604/log.zip) (not useful). The web client window was open in a browser causing the problem. This file was with the web client closed, and the problem with the WU downloads didn't happen yet: [log-20230106_060905.zip](https://github.com/FoldingAtHome/fah-client-bastet/files/10360657/log-20230106_060905.zip)

**Comment by jcoffland** [comment]
This should be fixed in the upcoming v8.1.8 release.

**Comment by joe-h-fah** [comment]
Still a problem on macOS.  A WU download hung on v8.1.8 this afternoon, no progress for ~2 hours.  Also kept the web control from connecting.

`18:08:54:I1::WU311:Core returned FINISHED_UNIT (100)
18:08:54:I1::Added new work unit: cpus:4 gpus:
18:08:54:I1::WU311:Uploading WU results
18:08:55:I1:OUT63:> POST https://vav19.fah.temple.edu/api/results HTTP/1.1
18:08:55:I3:Connecting to vav19.fah.temple.edu:443
18:08:55:I1::WU312:Requesting WU assignment
18:08:55:I1:OUT64:> POST https://assign4.foldingathome.org/api/assign HTTP/1.1
18:08:55:I3:Connecting to assign4.foldingathome.org:443
18:08:55:I1:OUT64:< assign4.foldingathome.org:443 HTTP/1.1 200 HTTP_OK
18:08:55:I1::WU312:Received WU assignment wyqpnOSuBCgyhnbWJ3V15cBx7d7koYFeVfiOSazO7BQ
18:08:55:I1::WU312:Downloading WU
18:08:55:I1:OUT65:> POST https://ds03.scs.illinois.edu/api/assign HTTP/1.1
18:08:55:I3:Connecting to ds03.scs.illinois.edu:443
18:08:58:I1:OUT63:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
18:08:58:I1::WU311:Credited`

This was using the release version, default logging verbosity.  WS ds03.scs.illinois.edu is the same as I have seen at least 3 other times result in a WU download hanging like this on versions prior to 8.1.8.

**Comment by jcoffland** [comment]
@joe-h-fah Can you post the full log?  There are two different WUs being processed here, WU311 and WU311.  WU311 finishes, uploads and receives credit.  WU312 gets assigned to a WS and starts to download but there's only 3 more seconds of the log.  This is the download attempt:

```
18:08:55:I1::WU312:Downloading WU
18:08:55:I1:OUT65:> POST https://ds03.scs.illinois.edu/api/assign HTTP/1.1
18:08:55:I3:Connecting to ds03.scs.illinois.edu:443
```

But what happens after that?  Is there any more mention of ``OUT65`` later in the log or is that it?  Particularly, there should be some sort of action by 18:10:00.

**Comment by joe-h-fah** [comment]
That is the end of the log, nothing entered for 2 hours.  I can post examples from previous download hangs, they are just the same as this.  WU finishes, new WU is requested as the first one is uploaded, Request is taken by AS and passed to a WS and after the connection message - nothing.

**Comment by joe-h-fah** [comment]
Here is the previous time this happened under 8.1.7:
`08:03:59:I1::WU295:Completed 2475000 out of 2500000 steps (99%)
08:06:00:I1::WU295:Completed 2500000 out of 2500000 steps (100%)
08:06:01:I1::WU295:Saving result file ../logfile_01.txt
08:06:01:I1::WU295:Saving result file frame219.gro
08:06:01:I1::WU295:Saving result file frame219.xtc
08:06:01:I1::WU295:Saving result file md.log
08:06:01:I1::WU295:Saving result file science.log
08:06:01:I1::WU295:Saving result file state.cpt
08:06:01:I1::WU295:Folding@home Core Shutdown: FINISHED_UNIT
08:06:02:I1::WU295:Core returned FINISHED_UNIT (100)
08:06:02:I1::Added new work unit: cpus:4 gpus:
08:06:02:I1::WU295:Uploading WU results
08:06:02:I1:OUT43:> POST https://vav19.fah.temple.edu/api/results HTTP/1.1
08:06:02:I3:Connecting to vav19.fah.temple.edu:443
08:06:02:I1::WU296:Requesting WU assignment
08:06:02:I1:OUT44:> POST https://assign1.foldingathome.org/api/assign HTTP/1.1
08:06:02:I3:Connecting to assign1.foldingathome.org:443
08:06:03:I1:OUT44:< assign1.foldingathome.org:443 HTTP/1.1 200 HTTP_OK
08:06:03:I1::WU296:Received WU assignment upMIy28Ryt2aIqUubMlO6zyyol6L5a0OzabsiyojJp8
08:06:03:I1::WU296:Downloading WU
08:06:03:I1:OUT45:> POST https://ds03.scs.illinois.edu/api/assign HTTP/1.1
08:06:03:I3:Connecting to ds03.scs.illinois.edu:443
08:06:06:I1:OUT43:< vav19.fah.temple.edu:443 HTTP/1.1 200 HTTP_OK
08:06:06:I1::WU295:Credited
22:03:17:I1:Clean exit
`
The time stamp for the start of WU295 is 2023-01-07T04:28:12Z.  The "Clean exit" was me pausing the client as I could still use the web control that time, as can be seen nothing had happened for 14 hours with the WU download attempt.

**Comment by jcoffland** [comment]
I think you may have been running v8.1.7.  I checked the vav19 server logs for the successful return of WU295.  The only entry that looks like a match for what you posted above is at 08:06:05 on Jan. 8th.  In the log the OS is macOS, the client version is 8.1.7 and it has your user name.  The WU returned was p16977 r6 c1804 g219.  Is this what you have for WU295?  I cannot be 100% sure I've got the right log entry but unless your system's clock is off, there's no other log entry that makes sense.

**Comment by joe-h-fah** [comment]
The second log section I just posted I did explicitly say was for 8.1.7 - "Here is the previous time this happened under 8.1.7".  The log section I posted before that definitely was for 8.1.8.  Look up the return of WU311 to vav19 at Temple at 18:08:58 yesterday.

**Comment by jcoffland** [comment]
Right, I see you did say it was from v8.1.7.  My bad.

So as of now we only have one instance on v8.1.8+ were it appears to have hung and that is this WU312 at 18:08:55 on Jan. 10th.  I can actually see the request on ds03.scs.illinois.edu and it appears to have assigned the WU.  So it was not a connection failure.  It says you were assigned P19209:R11:C1:G91.

**Comment by joe-h-fah** [comment]
So it assigned a WU, but it never downloaded from ds03 to my Mac, no files in the work directory connected to that assignment.  The client never detected that failure to finish the download and retry it.  From the server status page I see ds03 is running the same version as most of the other active servers.  So I would guess the problem is within the client code unless there is some odd setting on this server side.  In either case the connection "hung".

**Comment by jcoffland** [comment]
Maybe there's a problem with read timeouts.  I'll look into it.

**Comment by jcoffland** [comment]
I think I found the problem.  There was a bug that could cause timeouts to not trigger in some cases on Windows or macOS.  The new code will be in v8.1.10.

**Comment by jcoffland** [comment]
Fixed in v8.1.10
